name: Deploy to TestFlight

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true # this will automatically install Bundler and gems listed in Gemfile.lock, and cache them between builds

    - name: Install fastlane
      run: gem install fastlane

    - name: Deploy to TestFlight
      working-directory: ./ios
      run: fastlane ios beta
      env:
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
